# Generated by Django 4.0.3 on 2022-05-21 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_code', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)])),
                ('item_name', models.CharField(default='', max_length=1000)),
                ('item_quant', models.IntegerField(default=0)),
                ('item_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
