# Generated by Django 4.0.3 on 2022-05-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_alter_list_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='list',
            name='item_price',
        ),
        migrations.AlterField(
            model_name='list',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.items'),
        ),
    ]
