# Generated by Django 4.0.3 on 2022-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_rename_cust_id_list_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='UID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
