# Generated by Django 4.0.3 on 2022-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_alter_items_item_price_alter_items_item_quant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_quant',
            field=models.IntegerField(default=0),
        ),
    ]
