# Generated by Django 4.0.3 on 2022-05-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0010_alter_items_item_price_alter_items_item_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_app.invoice'),
        ),
        migrations.AlterField(
            model_name='list',
            name='item_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='list',
            name='item_quant',
            field=models.IntegerField(default='0'),
        ),
    ]
