# Generated by Django 4.0.3 on 2022-05-24 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0013_list_item_price_alter_list_item_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
