# Generated by Django 4.0.3 on 2022-05-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0017_list_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='item_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
