# Generated by Django 4.0.3 on 2022-05-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0019_list_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='total_price',
        ),
    ]
